# Generated by Django 5.2.5 on 2025-08-19 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Раздел')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ('ordering', 'name'),
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Элемент'),
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Подраздел')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='Слаг')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='core.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Подраздел',
                'verbose_name_plural': 'Подразделы',
                'ordering': ('section__ordering', 'ordering', 'name'),
                'unique_together': {('section', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Subsubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Подподраздел')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='Слаг')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubsections', to='core.subsection', verbose_name='Подраздел')),
            ],
            options={
                'verbose_name': 'Подподраздел',
                'verbose_name_plural': 'Подподразделы',
                'ordering': ('subsection__section__ordering', 'subsection__ordering', 'ordering', 'name'),
                'unique_together': {('subsection', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.subsubsection', verbose_name='Подподраздел'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
