# Generated by Django 5.2.5 on 2025-08-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='section',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='section_icons/', verbose_name='Иконка'),
        ),
    ]
