# Generated by Django 5.2.5 on 2025-09-09 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_section_color_section_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Элементы', to='core.subsection', verbose_name='Подподраздел'),
        ),
        migrations.DeleteModel(
            name='Subsubsection',
        ),
    ]
