# Generated by Django 5.2.5 on 2025-09-11 07:32

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_item_node_delete_subsubsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=core.models.item_video_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm', 'mkv'])], verbose_name='Видео'),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.item_image_upload_to, verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.item', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ('ordering', 'id'),
            },
        ),
    ]
