# Generated by Django 5.2.5 on 2025-09-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_video_itemimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='caption',
        ),
    ]
