# Generated by Django 5.2.6 on 2025-09-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_itemimage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='display_images_count',
            field=models.PositiveIntegerField(default=0, help_text='0 — показывать все', verbose_name='Количество отображаемых изображений'),
        ),
    ]
